//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFoy6
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBolum
    {
        public tBolum()
        {
            this.tOgrencis = new HashSet<tOgrenci>();
        }
    
        public int bolumID { get; set; }
        public string bolumAd { get; set; }
        public int fakulteID { get; set; }
    
        public virtual tFakulte tFakulte { get; set; }
        public virtual ICollection<tOgrenci> tOgrencis { get; set; }
    }
}
