//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFoy6
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOgrenci
    {
        public int ogrenciID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public int bolumID { get; set; }
    
        public virtual tBolum tBolum { get; set; }
    }
}
