USE vtys7hafta
GO
CREATE TABLE Urun(
Id INT PRIMARY KEY IDENTITY(1,1),
Ad NVARCHAR(50),
Fiyat INT,
Stok INT
)

CREATE TABLE Siparis(
Id INT PRIMARY KEY IDENTITY(1,1),
UrunId INT,
Miktar INT,
Tarih DATETIME
FOREIGN KEY (UrunId) REFERENCES Urun(Id)
)
